import {actions} from './simulation/actions.js';
export function createUI(characters,furniture,simulation,onHome){
 document.querySelector('#app').innerHTML=`<header><a class="brand" href="./"><span class="brand-mark">ち<span>ぴ</span></span><div>ちきぴよ暮らし<small>CHIKI & PIYO · LITTLE FUTURE HOME</small></div></a><div class="header-note"><span class="live-dot"></span>ふたりの、小さな毎日。</div><button id="pause" class="button">Ⅱ 一時停止</button></header><main><section class="world"><div class="scene-heading"><div class="eyebrow">HOME, SWEET PRINTED HOME</div><h1>小さな未来のおうち</h1><p>なんでもない一日を、いっしょに。</p></div><div class="weather">☀ <span>ぽかぽか日和<small>おうち時間 <b id="clock">09:00</b></small></span></div><div id="canvas-host" aria-label="ちきとぴよの3Dドールハウス"></div><div class="scene-bottom"><span class="scene-badge"><i class="live-dot"></i><span id="world-state">ふたりは自由に暮らしています</span></span><button id="home" class="button round" title="視点をリセット" aria-label="視点をリセット">⌂</button></div><div class="camera-help">ドラッグで回転 <span>·</span> スクロールでズーム <span>·</span> 右ドラッグで移動</div></section><aside><div class="section-title"><h2>いま、なにしてる？</h2><span>ふたりのようす</span></div><div class="character-list">${characters.map((c,i)=>`<button class="character-card ${i===0?'selected':''}" data-character="${c.id}" aria-pressed="${i===0}"><span class="avatar ${c.id}">${i===0?'ち':'ぴ'}</span><span class="character-copy"><strong>${c.name}</strong><span id="status-${c.id}">ひとやすみ</span></span><span class="selection-dot"></span></button>`).join('')}</div><div class="activity-title"><h2>なにをしよう？</h2><p><b id="selected-name">${characters[0].name}</b>に、過ごし方をおすそわけ。</p></div><div id="furniture-grid">${furniture.map(f=>`<button class="furniture-button" data-furniture="${f.id}"><span>${f.icon}</span><strong>${f.name}</strong><small>${f.label} ↗</small></button>`).join('')}</div><p class="hint">おうちの家具をクリックしても選べます。</p><section class="diary"><h2><span>⌁</span> おうちのひとこま</h2><div id="events" aria-live="polite"><p>新しい一日が、はじまりました。</p></div></section><div class="aside-footer">ゆっくり、気ままに、ふたりらしく。<span>✳</span></div></aside></main><div id="action-popover" hidden><button id="close-popover" aria-label="閉じる">×</button><small id="popover-furniture"></small><strong id="popover-title"></strong><button id="perform-action" class="button primary">やってみる</button></div><div id="toast" role="status"></div><footer><span>CHIKI & PIYO</span><span>A LITTLE LIFE, PRINTED WITH LOVE.</span><span>ふたりの暮らしを見守ろう ↗</span></footer>`;
 let selected=characters[0],pending=null,toastTimer;const $=s=>document.querySelector(s);
 const toast=message=>{$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3000);};
 const selectFurniture=id=>{pending=furniture.find(f=>f.id===id);$('#popover-furniture').textContent=pending.name;$('#popover-title').textContent=`${selected.name}と${pending.label}`;$('#action-popover').hidden=false;};
 document.querySelectorAll('[data-character]').forEach(el=>el.onclick=()=>{selected=characters.find(c=>c.id===el.dataset.character);document.querySelectorAll('[data-character]').forEach(b=>{b.classList.toggle('selected',b===el);b.setAttribute('aria-pressed',b===el);});$('#selected-name').textContent=selected.name;if(pending)$('#popover-title').textContent=`${selected.name}と${pending.label}`;});
 document.querySelectorAll('[data-furniture]').forEach(el=>el.onclick=()=>selectFurniture(el.dataset.furniture));
 $('#close-popover').onclick=()=>$('#action-popover').hidden=true;
 $('#perform-action').onclick=()=>{const ok=simulation.command(selected,pending.id);toast(ok?`${selected.name}が${pending.name}へ。${simulation.paused?'再開すると動きます。':''}`:'いまはもうひとりが使っています。あとで試してね。');$('#action-popover').hidden=true;};
 document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#action-popover').hidden=true;});
 $('#pause').onclick=()=>{simulation.paused=!simulation.paused;$('#pause').textContent=simulation.paused?'▶ 再開する':'Ⅱ 一時停止';$('#world-state').textContent=simulation.paused?'ふたりの時間を一時停止中':'ふたりは自由に暮らしています';$('#pause').setAttribute('aria-pressed',simulation.paused);};$('#home').onclick=onHome;
 return {selectFurniture,event(message){const p=document.createElement('p');p.textContent=message;$('#events').prepend(p);while($('#events').children.length>3)$('#events').lastChild.remove();},update(){for(const c of characters)$(`#status-${c.id}`).textContent=c.phase==='walking'?`${c.target.name}へ、てくてく` : actions[c.action].label;const minutes=540+Math.floor(simulation.time*2);$('#clock').textContent=`${String(Math.floor(minutes/60)%24).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;}};
}

